services:
  qrdinamic:
    build: .
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: ${APP_PORT:-3000}
      DATA_FILE_PATH: /app/data/qrs.json
      FALLBACK_URL: ${FALLBACK_URL:-/qr/not-found}
      PUBLIC_BASE_URL: ${PUBLIC_BASE_URL}
    expose:
      - "3107"
    labels:
      - traefik.enable=true
      - traefik.docker.network=dokploy-network
      # HTTP
      - traefik.http.routers.qrdinamic-http.rule=Host(`qr.dofer.mx`)
      - traefik.http.routers.qrdinamic-http.entrypoints=web
      - traefik.http.routers.qrdinamic-http.service=qrdinamic-svc
      # HTTPS
      - traefik.http.routers.qrdinamic-https.rule=Host(`qr.dofer.mx`)
      - traefik.http.routers.qrdinamic-https.entrypoints=websecure
      - traefik.http.routers.qrdinamic-https.tls=true
      - traefik.http.routers.qrdinamic-https.tls.certresolver=letsencrypt
      - traefik.http.routers.qrdinamic-https.service=qrdinamic-svc
      # Servicio
      - traefik.http.services.qrdinamic-svc.loadbalancer.server.port=3107
    networks:
      - dokploy-network
    volumes:
      - qrdinamic_data:/app/data

volumes:
  qrdinamic_data:

networks:
  dokploy-network:
    external: true
